/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kyle' at '12/6/14 4:57 PM' with Gradle 2.2
 *
 * @author Kyle, @date 12/6/14 4:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
